version: '3.8'

services:
  user-registration-service:
    build:
      context: ./user-registration-service
      dockerfile: Dockerfile
    image: tradestream-user-registration-service:dev
    ports:
      - "8081:8081" 
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authdb
      SPRING_DATASOURCE_USERNAME: authuser
      SPRING_DATASOURCE_PASSWORD: authpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
    deploy:
      replicas: 1
  auth-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    image: tradestream-auth-service:dev
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authdb
      SPRING_DATASOURCE_USERNAME: authuser
      SPRING_DATASOURCE_PASSWORD: authpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private.pem
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public.pem
    deploy:
      replicas: 1
    secrets:
      - jwt_private.pem
      - jwt_public.pem
  market-data-consumer:
    build:
      context: ./market-data-consumer
      dockerfile: Dockerfile
    image: market-data-consumer:dev
    ports:
      - "8083:8083"
    depends_on:
      - market_postgres
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://market_postgres:5432/marketdb
      SPRING_DATASOURCE_USERNAME: marketuser
      SPRING_DATASOURCE_PASSWORD: marketpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
    deploy:
      replicas: 1
  transaction-processor:
    build:
      context: ./transaction-processor
      dockerfile: Dockerfile
    image: transaction-processor:dev
    ports:
      - "8084:8084"
    depends_on:
      - transaction_postgres
      - market-data-consumer
    environment:
      SERVER_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:postgresql://transaction_postgres:5432/transactiondb
      SPRING_DATASOURCE_USERNAME: transactionuser
      SPRING_DATASOURCE_PASSWORD: transactionpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      MARKET_SERVICE_URL: http://market-data-consumer:8083
    deploy:
      replicas: 1
  postgres:
    image: postgres:15-alpine
    container_name: tradestream_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  market_postgres:
    image: postgres:15-alpine
    container_name: market_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: marketdb
      POSTGRES_USER: marketuser
      POSTGRES_PASSWORD: marketpass
    volumes:
      - market_postgres_data:/var/lib/postgresql/data
  transaction_postgres:
    image: postgres:15-alpine
    container_name: transaction_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: transactiondb
      POSTGRES_USER: transactionuser
      POSTGRES_PASSWORD: transactionpass
    volumes:
      - transaction_postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data:
  market_postgres_data:
  transaction_postgres_data:


secrets:
  jwt_private.pem:
    external: true
  jwt_public.pem:
    external: true
