spring:
  application:
    name: ${APP_NAME:service}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    open-in-view: false
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: ${SPRING_FLYWAY_LOCATIONS:classpath:db/migration}
    baseline-on-migrate: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  server:
    port: ${MANAGEMENT_PORT:${SERVER_PORT}}   # keep health on same port for docker healthchecks

logging:
  level:
    root: INFO
    org.flywaydb: DEBUG


# --- JWT / JOSE paths (mounted as Docker secrets) ---
auth:
  jwt:
    privateKeyPath: ${JWT_PRIVATE_KEY_PATH:/run/secrets/jwt_private.pem}
    publicKeyPath:  ${JWT_PUBLIC_KEY_PATH:/run/secrets/jwt_public.pem}

# Optional: actuator info to confirm which keys loaded
info:
  app: auth-service
  jwtPublicKeyPath: ${JWT_PUBLIC_KEY_PATH:/run/secrets/jwt_public.pem}
