spring:
  application:
    name: orders-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: ${SPRING_FLYWAY_LOCATIONS:classpath:db/migration}
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:redpanda:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false   # 👈 move here (applies to JsonSerializer)

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:orders-exec-consumer}
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.tradestream.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.tradestream.orders_service.dto.TradeExecuted
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${SERVER_PORT:8085}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  server:
    port: ${MANAGEMENT_PORT:${SERVER_PORT}}

logging:
  level:
    root: INFO
    org.flywaydb: DEBUG
    org.springframework.web: DEBUG

tradestream:
  topics:
    orderPlaced: ${KAFKA_TOPIC_ORDER_PLACED:order.placed.v1}
    orderCancelled: ${KAFKA_TOPIC_ORDER_CANCELLED:order.cancelled.v1}
    tradeExecuted: ${KAFKA_TOPIC_TRADE_EXECUTED:trade.executed.v1}
